name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string
      aws-assume-role-arn:
        description: "The role to assume"
        required: true
        type: string
      aws-state-file:
        description: "The S3 state file"
        required: true
        type: string
      aws-region:
        description: "The AWS region"
        required: true
        type: string
      aws-lock-dynamo-table:
        description: "The DynamoDB table for state locking"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_actions
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: |
          cd tf-infra && terraform init \
            -backend-config="bucket=${{ inputs.aws-state-file }}" \
            -backend-config="key=${{ github.event.repository.name }}" \
            -backend-config="region=${{ inputs.aws-region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamo-table }}"

      - name: Terraform Validate
        run: terraform validate
        

              



            

